### ISSUE TITLE
linter crash from :: bind operator in JSX

### ISSUE THREAD

**Issue by tsheaff** [evcohen/jsx-ast-utils#39] opened 2017-05-19 19:53 UTC
Migrated from https://github.com/babel/babel-eslint/issues/472

I'm using [this syntax](https://github.com/tc39/proposal-bind-operator):

`::this.foo()`

However, eslint crashes in this case:

```
The prop value with an expression type of BindExpression could not be resolved.
  Please file issue to get this fixed immediately.
Error: The prop value with an expression type of BindExpression could not be resolved.
  Please file issue to get this fixed immediately.
    at Object.extract [as JSXExpressionContainer] (/Users/tsheaff/Code/private/calm/www/node_modules/jsx-ast-utils/lib/values/expressions/index.js:173:11)
    at getValue (/Users/tsheaff/Code/private/calm/www/node_modules/jsx-ast-utils/lib/values/index.js:48:27)
    at extractValue (/Users/tsheaff/Code/private/calm/www/node_modules/jsx-ast-utils/lib/getPropValue.js:24:12)
    at getPropValue (/Users/tsheaff/Code/private/calm/www/node_modules/jsx-ast-utils/lib/getPropValue.js:41:10)
    at /Users/tsheaff/Code/private/calm/www/node_modules/eslint-plugin-jsx-a11y/lib/rules/no-static-element-interactions.js:76:95
    at Array.some (native)
    at EventEmitter.JSXOpeningElement (/Users/tsheaff/Code/private/calm/www/node_modules/eslint-plugin-jsx-a11y/lib/rules/no-static-element-interactions.js:75:52)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:191:7)
    at NodeEventGenerator.applySelector (/Users/tsheaff/Code/private/calm/www/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/tsheaff/Code/private/calm/www/node_modules/eslint/lib/util/node-event-generator.js:294:22)
```

Here is my `.eslintrc`:

```
module.exports = {
  'env': {
    'browser': true,
    'node': true,
  },
  'plugins': [ 'react' ],
  'parser': 'babel-eslint',
  'extends': 'airbnb', /* see https://github.com/airbnb/javascript */
  'rules': {
    /* override a few airbnb rules */
    'strict': 0,
    'space-before-function-paren': ['error', 'never'],
    'func-names': 'off',
    'no-console': 'error',
    'max-len': 'off',
    'global-require': 'error',
    'consistent-return': 'off',
    'class-methods-use-this': 'off',
    'object-shorthand': ['error', 'never'],
    'no-param-reassign': ['error', {
      'props': false
    }],
    'brace-style': ['error', '1tbs', { allowSingleLine: false }],
    'arrow-parens': ['error', 'always'],
    'arrow-body-style': 'off',
    'import/prefer-default-export': 'off',
    'import/extensions': ['error', {
      'js': 'never',
      'json': 'always'
    }],
  },
}
```

Here are my dependencies:

```
    "babel-eslint": "^7.2.3",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.1",
```

When I remove the `'parser': 'babel-eslint',` line from the config, this crash goes away.  However in that case native eslint doesn't recognize the `::` and says `Parsing error: Unexpected token : (Fatal)` It also goes away if the file I'm linting does not use the `::` syntax

This mini-repo recreates the error: https://gist.github.com/tsheaff/003685ca6a163fb467a29fb7c70fbf10

The `::` operator on line [this line](https://gist.github.com/tsheaff/003685ca6a163fb467a29fb7c70fbf10#file-index-js-L16) is the offending one. If I remove that or switch to `.bind(this)` syntax I don't get the error.  I also don't get the error if the `::` is not in JSX

**Comment by tsheaff** [comment] 2017-05-19 19:55
the reason is that it doesn't account for `::` because it's using acorn-jsx instead of babylon. the rule would need to update it's version of that util

**Comment by ljharb** [comment] 2017-05-19 20:00
Duplicate of #33.

**Closed** 2017-05-19 20:08 UTC
